name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint code
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci
      - name: Run Eslint
        run: npm run ci:lint
      - name: Run Tests
        run: npm run ci:test
      - name: Build
        run: npm run build
